[connections.hol-timeseries]
account = "sfsenorthamerica-demo156"
user = "USER_HOL_TIMESERIES"
role = "ROLE_HOL_TIMESERIES"
database = "HOL_TIMESERIES"
schema = "STAGING"
warehouse = "TS_HOL_ANALYTICS_WH"
authenticator = "SNOWFLAKE_JWT"
private_key_path = "keys/rsa_key.p8"

[connections.hol-timeseries-streamlit]
account = "sfsenorthamerica-demo156"
user = "USER_HOL_TIMESERIES"
role = "ROLE_HOL_TIMESERIES"
database = "HOL_TIMESERIES"
schema = "ANALYTICS"
warehouse = "TS_HOL_ANALYTICS_WH"
authenticator = "SNOWFLAKE_JWT"
private_key_path = "keys/rsa_key.p8"